--------------------------------------------------------
--  File created - poniedziałek-grudnia-24-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DOKUMENT
--------------------------------------------------------

  CREATE TABLE "C##PPAWLUK"."DOKUMENT" 
   (	"NAZWA_DOKUMENTU" VARCHAR2(200 BYTE), 
	"TEKST" VARCHAR2(4000 BYTE), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##PPAWLUK.DOKUMENT
SET DEFINE OFF;
Insert into C##PPAWLUK.DOKUMENT (NAZWA_DOKUMENTU,TEKST,ID) values ('D20181943.txt',' godło napis bóg ojczyzna napis bóg honor ojczyzna napis bóg honor ojczyzna kształt półkole litera wysokość centymetr wykonać kolor złoty wzór strona główny płat sztandar określić załącznik numer rozporządzenie strona odwrotny płat sztandar środek płat znajdować wizerunek święty wysokość centymetr wizerunek święty umieszczać pełny nazwa jednostka wizerunek święty nazwa siedziba jednostka litera wysokość centymetr wykonać kolor srebrny dolny róg strona odwrotny płat sztandar umieszczać lewa róg rok powołanie jednostka prawa róg rok nadanie sztandar wzór strona odwrotny płat sztandar określić załącznik numer rozporządzenie strona odwrotny płat sztandar górny róg bycie umieścić herb miejscowość ziem oznaka pożarniczy państwowy straż pożarny emblemat inicjał fundator sztandar minister sprawa wewnętrzny administracja kierować dziać administracja rządowy sprawa wewnętrzny podstawa punkt rozporządzenie prezes rad minister dzień styczeń sprawa szczegółowy zakres działanie minister sprawa wewnętrzny administracja pozycja dziennik ustawa pozycja usta otrzymywać brzmienie drzewce sztandar długość centymetr wykonać drewno toczony średnica centymetr kolor ciemny orzech drzewce dwudzielny połączyć metalowy gwintować złącze drzewce bycie umieścić gwóźdź pamiątkowy złoty kolor dolny koniec drzewce umieścić stożkowaty metalowy okucie element metalowy drzewce wykonać kolor złoty załącznik numer rozporządzenie otrzymywać brzmienie określić załącznik numer niniejszy rozporządzenie załącznik numer rozporządzenie otrzymywać brzmienie określić załącznik numer niniejszy rozporządzenie sztandar jednostka organizacyjny państwowy straż pożarny','931');
Insert into C##PPAWLUK.DOKUMENT (NAZWA_DOKUMENTU,TEKST,ID) values ('D20181943.txt',' dotychczasowy wzór bycie używać czas nadanie jednostka sztandar wzór określić rozporządzenie zmieniać brzmienie nadać niniejszy rozporządzenie rozporządzenie wchodzić życie upływ dzień dzień ogłosić minister sprawa wewnętrzny administracja w zastępstwie dziennik ustawa załącznik rozporządzenie minister sprawa wewnętrzny wrzesień minister rok pozycja rozporządzenie sprawa wewnętrzny administracja dzień wrzesień rok pozycja załącznik numer załącznik numer alba dziennik ustawa pozycja dziennik ustawa załącznik numer pozycja załącznik numer poz dziennik ustaw załącznik nr poz załącznik nr','932');
Insert into C##PPAWLUK.DOKUMENT (NAZWA_DOKUMENTU,TEKST,ID) values ('D20181937.txt',' identyfikacja doświadczenie skarga mianowicie skarga antynomiczny październik pozycja wyrok trybunał konstytucyjny dzień październik akt trybunał konstytucyjny skład przewodniczyć tuleja sprawozdawca rozpoznanie tryb punkt ustawa dzień listopad organizacja tryb postępowanie trybunał konstytucyjny pozycja posiedzenie niejawny dzień październik skarga konstytucyjny zbadanie zgodność ustawa dzień czerwiec kodeks postępowanie karny numer pozycja zmarły zakres wyłączać dopuszczalność zaskarżyć zażalenie postanowienie wydać podstawa kodeks postępowanie karny odnosić oskarżyciel posiłkowy mowa kodeks postępowanie karny związek artykuł konstytucja rzeczpospolita polski orzekać artykuł ustawa dzień czerwiec kodeks postępowanie karny numer pozycja zmarły brzmienie obowiązujący czerwiec to jest dzień poprzedzać wejście życie artykuł punkt ustawa dzień wrzesień zmiana ustawa kodeks postępowanie karny niektóry ustawa pozycja zakres wyłączać dopuszczalność zaskarżyć zażalenie postanowienie wydać podstawa artykuł ustawa kodeks postępowanie karny odnosić oskarżyciel posiłkowy uboczny niezgodny artykuł związek artykuł usta konstytucja rzeczpospolita polski ponadto postanawiać podstawa artykuł usta punkt ustawa dzień listopad organizacja tryb postępowanie trybunał konstytucyjny pozycja umorzyć postępowanie pozostały zakres orzec zapadły jednogłośnie tuleja umorzyć postępowanie pozostałym zakresie orzeczenie zapadło jednogłośnie jędrzejewski tuleja pszczółkowski kieres zielonacki','929');
Insert into C##PPAWLUK.DOKUMENT (NAZWA_DOKUMENTU,TEKST,ID) values ('D20181943.txt',' emisja emisja alarmowy wzajemnie nieopodal analogiczny listowie desygnacja egzystencja awatar państwowy stukać egzystencja egzystencja miast zmieniać rozporządzenie sprawa określenie wzór tryb nadawanie sztandar jednostka organizacyjny państwowy straż pożarny podstawa ustawa dzień sierpień państwowy straż pożarny pozycja zarządzać następować rozporządzenie minister sprawa wewnętrzny dzień lipiec sprawa określenie wzór tryb nadawanie sztandar jednostka organizacyjny państwowy straż pożarny pozycja pozycja wprowadzać następować zmiana otrzymywać brzmienie płat sztandar tkanina kształt kwadrat bok długość centymetr kolor czerwone zbliżony kolor czerwienić sygnałowy metr strona główny błękitny zbliżony kolor błękit lazur metr strona odwrotny obszyć obustronnie wzdłuż obwód złoty taśma szerokość centymetr trzy strona złoty frędzla długość centymetr strona główny płat sztandar znajdować równoramienny krzyż kolor biały długość ramię równy wymiar płat sztandar kształt podobny państwowy odznaczenie krzyż zasług szerokość ramię krzyż krawędź strona główny płat sztandar wynosić centymetr pośrodek krzyż umieścić godło państwowy okrągły czerwona tarcza średnica centymetr obramować biała krawędź szerokość centymetr wieniec stylizować liście laurowy kolor złoty szerokość centymetr odstęp centymetr strona zewnętrzny wieniec biec pierścienić kolor złoty szerokość centymetr godło rzeczpospolita polski przedstawiać wizerunek orzeł biały ustalić ustawa dzień styczeń godło barwa hymn rzeczpospolita polski pieczęć państwowy pozycja wysokość godło wynosić centymetr strona główny płat sztandar umieszczać górny częsty godło napis służba dolny częsty','930');
Insert into C##PPAWLUK.DOKUMENT (NAZWA_DOKUMENTU,TEKST,ID) values ('D20181947.txt',' klauzula klauzula likwidacja dostatek konferansjerka manipulacja praktyczny negocjacje liczyć klauzula kamizelka rodzina dostatek kamizelka konferencja egzystencja nauka nauka egzystencja spodziewany konferansjerka przybierać droga egzystencja likwidacja miast akustyk cybernetyczny cybernetyczny Internet nazwa wpływać kalkulacja namiar konferansjerka konferansjerka ciek ciek marka cybernetyczny cybernetyczny Internet naprawiacz nazwa wpływać ciek akustyk konferansjerka konferansjerka marka kamizelka klauzula kamizelka kamizelka klauzula kamizelka administracja morski zwać dalej ustawa ramowy program szkolenie hydrograf morski tryb uzyskiwać wzór dyplom hydrograf morski kategoria kategoria tryb weryfikacja uznawać instytucja organizacja ośrodek szkolenie prowadzić szkolenie hydrograf kategoria zwać dalej instytucja organizacja ośrodek szkolenie warunek cofnięcie uznanie podmiot ubiegać ponowny uznanie wykonywać pomiar hydrograficzny polski obszar morski potrzeba bezpieczeństwo żegluga kartografia morski projektować kontrola budowla hydrotechniczny planowanie przestrzenny ochrona środowisko wymagać posiadanie hydrograf morski kategoria wiedza teoretyczny umiejętność praktyczny pozwalać samodzielny planowanie prowadzenie nadzorować kompleksowy praca hydrograficzny realizować kontrola jakość praca hydrograficzny autoryzować wykonać praca hydrograficzny wykonywać zadanie zabezpieczenie hydrograficzny działalność ludzki morze hydrograf morski kategoria wiedza teoretyczny umiejętność praktyczny pozwalać samodzielny przygotowanie sprzęt niezbędny pomiar prowadzić rama praca hydrograficzny wykonywać pomiar wykorzystanie różnorodny system urządzenie pomiarowy uwzględnienie błąd ograniczenie stosowany urządzenie dokonywać bieżeć kontrola pomiar wstępna opracowanie wynik dziennik ustawa pozycja ustalenie wymagać okres praktyk hydrograf morski kategoria przyjmować dzień dzienia praktyk uznawać','933');
Insert into C##PPAWLUK.DOKUMENT (NAZWA_DOKUMENTU,TEKST,ID) values ('D20181947.txt',' wykonywać praca związać pomiar hydrograficzny wymiar godzina przyjmować dzień dzienia praktyk uznawać wykonywać praca związać pomiar hydrograficzny wymiar godzina okres praktyk wliczać praca związać pomiar hydrograficzny odbyć szkolenie mowa artykuł usta punkt ustawa wykonywać nadzór hydrograf morski posiadać dyplom hydrograf morski kategoria potwierdzić podpis podpis jednostka odbywać praktyk ramowy program szkolenie hydrograf morski określać minimalny zakres tematyka zagadnienie uwzględniać instytucja organizacja ośrodek szkolenie odpowiedni wymaganie kwalifikacyjny hydrograf morski kategoria ramowy program szkolenie hydrograf morski kategoria określić załącznik numer rozporządzenie określić załącznik numer rozporządzenie dyplom hydrograf morski wydawać wniosek wydanie dyplom hydrograf morski kategoria złożony szef biuro hydrograficzny marynarka wojenny zwać dalej szef wniosek wydanie dyplom hydrograf morski zawierać imię nazwisko numer pesel numer paszport dowód osobisty adres korespondencja numer telefon adres poczet elektroniczny podpis wnioskodawca wniosek wydanie dyplom hydrograf morski dołączać dokument potwierdzający posiadanie wykształcenie mowa artykuł usta punkt ustawa dokument potwierdzający odbyt szkolenie mowa artykuł usta punkt ustawa dokument potwierdzający odbyt praktyk mowa artykuł usta punkt ustawa fotograf szef termin dzień dzień wpływ wniosek wzywać wnioskodawca forma pisemny uzupełnienie brak formalny wydawać dyplom hydrograf morski dyplom hydrograf morski wydawać wnioskodawca siedziba biuro hydrograficzny marynarka wojenny pisemny potwierdzenie fakt odbiór wzór dyplom hydrograf morski kategoria określić załącznik numer rozporządzenie określić','934');
Insert into C##PPAWLUK.DOKUMENT (NAZWA_DOKUMENTU,TEKST,ID) values ('D20181947.txt',' załącznik numer rozporządzenie dziennik ustawa pozycja weryfikacja instytucja organizacja ośrodek szkolenie odbywać rozpatrzenie wniosek akceptacja program szkolenie złożony instytucja organizacja ośrodek szkolenie szef rozpatrywać wniosek mowa usta termin dzień dzień wpływ informować instytucja organizacja ośrodek szkolenie uznanie odmowa uznanie wniosek mowa usta zawierać następować informacja nazwa cel szkolenie ogólny struktura program obejmować charakterystyka poszczególny grupa przedmiot moduł szkoleniowy wraz część szkolenie praktyczny seminarium ćwiczenia terenowy egzamin czas trwanie poszczególny moduł przedmiot całkowity liczba godzina wykład laboratorium kierować kierować ćwiczenia praktyczny przewidywać student uczestnik szczegółowy kart przedmiot przedmiot przewidzieć program zawierać cel kształcenie przedmiot szczegółowy wykaz temat wykład ćwiczenia laboratorium podanie liczba godzina zamierzyć efekt kształcenie wskazanie odniesienie określić element szkoleniowy klasyfikacja podać ramowy program szkolenie mowa czas trwanie szkolenie okres wyrazić tydzień semestr miejsce planować zajęcia teoretyczny praktyczny oczekiwany wielkość poszczególny grupa szkoleniowy dana kadr dydaktyczny planować prowadzenie zajęcia podanie kwalifikacja naukowy doświadczenie hydrograficzny dorobek publikacyjny wykładowca instruktor wyposażenie dydaktyczny ćwiczenia praktyczny laboratorium lista charakterystyka wyposażenie techniczny pakiet specjalistyczny oprogramowanie hydrograficzny przewidzieć realizacja zajęcia dany szkolenie wykaz literatura środek mapa środek audiowizualny maić wykorzystywać czas szkolenie oferować dodatkowy moduł szkoleniowy zasada oceniać egzaminować zakończenie szkolenie hydrograf morski instytucja organizacja ośrodek szkolenie przedstawiać szef sprawozdanie zawierać informacja szkolenie osiągnąć rezultat wraz','935');
Insert into C##PPAWLUK.DOKUMENT (NAZWA_DOKUMENTU,TEKST,ID) values ('D20181947.txt',' lista absolwent zmiana program szkolenie hydrograf morski wymagać akceptacja szef szef cofnąć uznanie instytucja organizacja ośrodek szkolenie trakt trwanie szkolenie nastąpić zmiana informacja mowa usta bez wczesny uzgodnienie zmiana szef szef cofnąć uznanie instytucja organizacja ośrodek szkolenie powód negatywny wynik przeprowadzić weryfikacja szkolenie przypadek odmowa uznanie alba cofnięcie uznanie instytucja organizacja ośrodek szkolenie ubiegać ponowny uznanie przepis usta stosować odpowiedni rozporządzenie wchodzić życie upływ dzień dzień ogłosić minister obrona narodowy w zastępstwie dziennik ustawa pozycja załącznik rozporządzenie minister obrona narodowy dzień wrzesień rok pozycja załącznik numer ramowy program szkolenie hydrograf morski kategoria przedmiot ogólny matematyk statystyk teoria obserwacja geometria algebra liniowy rachunek różniczkowy równać różniczkowy rachunek prawdopodobieństwo statystyk informatyk technik komunikacja system komputerowy oprogramowanie biurowy element programować usługa sieciowy internet baza dana fizyk kinematyka grawimetria magnetyzm teoria fala fala elektromagnetyczny optyk geometryczny laser przetwornik pomiar czas nautyka środek system oznakowanie nawigacyjny światowy morski system łączność alarmowy bezpieczeństwo nawigacyjny mapa morski publikacja nautyczny kompas procedura bezpieczeństwo morze zasada bezpieczeństwo praca dobry praktyk morski lin kabel holować opuszczać przyrząd pomiarowy kotwiczyć cumować meteorologia podstawa meteorologia obserwacja meteorologiczny wiatr fala morski prognozować pogoda dziennik ustawa przedmiot podstawowy podstawa obliczenie kartograficzny geodezyjny geodezja fizyczny system współrzędna pomiar lądowy niwelacja odwzorować kartograficzny trygonometria teoria obserwacja metoda','936');
Insert into C##PPAWLUK.DOKUMENT (NAZWA_DOKUMENTU,TEKST,ID) values ('D20181947.txt',' mały kwadrat oceanografia masa wodny cyrkulacja geologia geofizyk geologia geofizyk morze przedmiot specjalistyczny pozycjonowanie system odniesienie statek przyrząd pomiarowy światowy system nawigacja satelitarny system inercjalny system nawigacja podwodny pozycjonowanie profil hydroakustyczny urządzenie pomiarowy podstawa hydroakustyk system jednowiązkowy system sonarowy system rozpraszanie wsteczny wiązka hydroakustyczny system laserowy teledetekcja hydrografia system laserowy teledetekcja prowadzenie pomiar hydrograficzny planowanie praca hydrograficzny prowadzenie praca hydrograficzny charakteryzować dna poziom woda pływ poziom woda woda pływowy pomiar poziom woda modelować pływ model odstęp elipsoidalny pionowy układ odniesienie przestrzenny prąd morski zbieranie opracowywać dana hydrograficzny pozyskiwać kontrolować dana pomiarowy czas rzeczywisty filtrować estymować dana batymetryczny pozycja dziennik ustawa pozycja zarządzanie dana hydrograficzny organizacja prezentacja dana źródło rozpowszechniać morski dana przestrzenny integracja wizualizacja dana przestrzenny gotowe produkt prawny aspekt praca hydrograficzny wiarygodność produkt morski strefa oznaczenie literowy przyjąć dokument międzynarodowy organizacja hydrograficzny dziennik ustawa pozycja załącznik numer ramowy program szkolenie hydrograf morski kategoria przedmiot ogólny matematyk statystyk teoria błąd algebra liniowy rachunek różniczkowy trygonometria statystyk teoria błąd metoda mały kwadrat interpolacja technologia informatyczny komunikacyjny system komputerowy oprogramowanie biurowy element programować usługa sieciowy internet baza dana fizyk mechanik grawimetria teoria fala nauka ziemia geografia geologia osad denny nautyka konwencjonalny środek oznakowanie nawigacyjny światowy morski system łączność alarmowy bezpieczeństwo nawigacyjny mapa','937');
Insert into C##PPAWLUK.DOKUMENT (NAZWA_DOKUMENTU,TEKST,ID) values ('D20181947.txt',' morski publikacja nautyczny kompas procedura bezpieczeństwo morze zasada bezpieczeństwo praca dobry praktyk morski lin kabel obsługa przyrząd pomiarowy holować opuszczać burta kotwiczyć cumować meteorologia podstawa obserwacja meteorologiczny wiatr prognozować pogoda bar dziennik ustawa pozycja przedmiot specjalistyczny hydroakustyk teoria akustyk echosonda jednowiązkowy sonar boczny system bar teledetekcja system laserowy teledetekcja poziom morze pływ zasada określać poziom morze pomiar poziom morze poprawka poziom morze prąd morski pozycjonowanie geodezja podstawa kartografia określać pozycja metoda technik określać wysokość hydroakustyczny system określać pozycja nawigacja inercjalny niepewność pozycjonowanie wykonywać praca hydrograficzny planowanie praca hydrograficzny prowadzenie praca hydrograficzny hydrograficzny dokumentacja pomiarowy prawny aspekt prowadzenie praca hydrograficzny zarządzanie dana hydrograficzny pozyskiwać kontrolować dana pomiarowy czas rzeczywisty opracowywać analiza dana organizacja prezentacja dana godzina nauka środowisko oceanografia geologia geofizyk morze wpływ środowisko pomiar hydrograficzny oznaczenie literowy przyjąć dokument międzynarodowy organizacja hydrograficzny dziennik ustawa pozycja załącznik numer wzór dyplom hydrograf morski kategoria dyplom hydrograf morski numer biuro hydrograficzny marynarka wojenny okaziciel niniejszy dyplom posiadać wiedza umiejętność doświadczenie wykonywać praca hydrograficzny stosownie wymaganie określić publikacja miejsce zdjąć kategoria imię nazwisko podpis posiadacz dyplom szef biuro hydrograficzny marynarka wojenny dzień dziennik ustawa pozycja załącznik numer wzór dyplom hydrograf morski kategoria bar dyplom hydrograf morski numer biuro hydrograficzny marynarka wojenny okaziciel niniejszy dyplom','938');
Insert into C##PPAWLUK.DOKUMENT (NAZWA_DOKUMENTU,TEKST,ID) values ('D20181947.txt',' posiadać wiedza umiejętność doświadczenie wykonywać praca hydrograficzny stosownie wymaganie określić publikacja bar for bar miejsce zdjąć kategoria bar imię nazwisko podpis posiadacz dyplom szef biuro hydrograficzny marynarka wojenny dzień prac hydrograficznych stosownie wymagań określonych publikacji iho standards of competence for category hydrographic surveyors miejsce zdjęcie kategoria imię nazwisko mp podpis posiadacza dyplomu szef biura hydrograficznego marynarki wojennej gdynia dnia','939');
Insert into C##PPAWLUK.DOKUMENT (NAZWA_DOKUMENTU,TEKST,ID) values ('D20181950.txt',' administracja publiczny urząd naczelna centralne organ administracja rządowy grupa wydatek bieżeć jednostka wynagrodzić osobowy członek korpus służba cywilny składka ubezpieczenie społeczny składka fundusz praca wynagrodzić bezosobowy odpis zakładowy fundusz świadczenie socjalna dziennik ustawa pozycja załącznik numer załącznik numer przeniesienie kwota wynagrodzenie przeniesienie kwota wynagrodzenie część dziać rozdziać wyszczególnienie zmniejszenie budownictwo planowanie zagospodarować przestrzenny mieszkalnictwo administracja publiczny urząd naczelna centralne organ administracja rządowy członek korpus służba cywilny informatyzacja administracja publiczny urząd naczelna centralne organ administracja rządowy członek korpus służba cywilny zwiększenie złoty zwiększenia zł','941');
Insert into C##PPAWLUK.DOKUMENT (NAZWA_DOKUMENTU,TEKST,ID) values ('D20181950.txt',' państwowy identyfikacja minimalizacja intensyfikacja państwowy benefit państwowy benefit identyfikacja minimalizacja państwowy państwowy intensyfikacja październik sprawa dokonanie przeniesienie niektóry planować wydatek budżet państwo kwota wynagrodzenie określić ustawa budżetowy rok podstawa ustawa dzień kwiecień zmiana ustawa dział administracja rządowy ustawa infrastruktura informacja przestrzenny pozycja zarządzać następować rozporządzenie określać przeniesienie niektóry planować wydatek budżet państwo kwota wynagrodzenie część budżet państwo zakres dotyczyć ministerstwo cyfryzacja ministerstwo inwestycja rozwój podział częsty dziać rozdziać budżet państwo przenosić planować wydatek budżet państwo wynagrodzić częsty informatyzacja częsty budownictwo planowanie zagospodarować przestrzenny mieszkalnictwo kwota złoty szczegółowy podziać planować wydatek mowa usta określać załącznik numer rozporządzenie rama przeniesienie mowa usta przenosić kwota wynagrodzenie częsty informatyzacja częsty budownictwo planowanie zagospodarować przestrzenny mieszkalnictwo zgodnie załącznik numer rozporządzenie rozporządzenie wchodzić życie dzień następować dzień ogłosić prezes rad minister załącznik rozporządzenie pozycja prezes rad minister załącznik rozporządzenie prezes rad minister dzień dzień październik pozycja dziennik ustawa załącznik numer załącznik numer przeniesienie planować wydatek budżet państwo przeniesienie planować wydatek budżet państwo część dziać rozdziać paragraf wyszczególnienie zmniejszenie zwiększenie złoty budownictwo planowanie zagospodarować przestrzenny mieszkalnictwo administracja publiczny urząd naczelna centralne organ administracja rządowy grupa wydatek bieżeć jednostka wynagrodzić osobowy członek korpus służba cywilny składka ubezpieczenie społeczny składka fundusz praca wynagrodzić bezosobowy odpis zakładowy fundusz świadczenie socjalna informatyzacja','940');
--------------------------------------------------------
--  DDL for Trigger DOKUMENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PPAWLUK"."DOKUMENT_TRG" 
BEFORE INSERT ON DOKUMENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT DOKUMENT_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PPAWLUK"."DOKUMENT_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table DOKUMENT
--------------------------------------------------------

  ALTER TABLE "C##PPAWLUK"."DOKUMENT" MODIFY ("NAZWA_DOKUMENTU" NOT NULL ENABLE);
  ALTER TABLE "C##PPAWLUK"."DOKUMENT" MODIFY ("ID" NOT NULL ENABLE);
